name: Update

on:
  schedule:
  - cron: '* * * * *'

jobs:
  update:
    name: Update bundle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - uses: actions/checkout@v2
      with:
        ref: test-update

    - name: Run go generate
      run: go generate

    - name: Commit files
      run: |
        tag=$(date +%Y.%m.%d)
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add certifi.go
        git commit -m "Update $tag"
        git push
